package model;
// Generated 05/03/2014 12:54:08 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Movimientoenc generated by hbm2java
 */
@Entity
@Table(name="movimientoenc"
    ,catalog="bdjpweb"
)
public class Movimientoenc  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private Cliente cliente;
     private Transaccion transaccion;
     private String fecha;
     private String total;
     private Set movimientodets = new HashSet(0);

    public Movimientoenc() {
    }

	
    public Movimientoenc(Usuario usuario, Cliente cliente, Transaccion transaccion, String fecha, String total) {
        this.usuario = usuario;
        this.cliente = cliente;
        this.transaccion = transaccion;
        this.fecha = fecha;
        this.total = total;
    }
    public Movimientoenc(Usuario usuario, Cliente cliente, Transaccion transaccion, String fecha, String total, Set movimientodets) {
       this.usuario = usuario;
       this.cliente = cliente;
       this.transaccion = transaccion;
       this.fecha = fecha;
       this.total = total;
       this.movimientodets = movimientodets;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_id", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente_id", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="transaccion_id", nullable=false)
    public Transaccion getTransaccion() {
        return this.transaccion;
    }
    
    public void setTransaccion(Transaccion transaccion) {
        this.transaccion = transaccion;
    }
    
    @Column(name="fecha", nullable=false, length=45)
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    
    @Column(name="total", nullable=false, length=45)
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="movimientoenc")
    public Set getMovimientodets() {
        return this.movimientodets;
    }
    
    public void setMovimientodets(Set movimientodets) {
        this.movimientodets = movimientodets;
    }




}


