package model;
// Generated 05/03/2014 12:54:08 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Movimientodet generated by hbm2java
 */
@Entity
@Table(name="movimientodet"
    ,catalog="bdjpweb"
)
public class Movimientodet  implements java.io.Serializable {


     private Integer id;
     private Movimientoenc movimientoenc;
     private Producto producto;
     private String precio;
     private String cantidad;

    public Movimientodet() {
    }

    public Movimientodet(Movimientoenc movimientoenc, Producto producto, String precio, String cantidad) {
       this.movimientoenc = movimientoenc;
       this.producto = producto;
       this.precio = precio;
       this.cantidad = cantidad;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="movimientoenc_id", nullable=false)
    public Movimientoenc getMovimientoenc() {
        return this.movimientoenc;
    }
    
    public void setMovimientoenc(Movimientoenc movimientoenc) {
        this.movimientoenc = movimientoenc;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="producto_id", nullable=false)
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    
    @Column(name="precio", nullable=false, length=45)
    public String getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(String precio) {
        this.precio = precio;
    }
    
    @Column(name="cantidad", nullable=false, length=45)
    public String getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }




}


