package model;
// Generated 05/03/2014 12:54:08 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="producto"
    ,catalog="bdjpweb"
)
public class Producto  implements java.io.Serializable {


     private Integer id;
     private Proveedor proveedor;
     private Categoria categoria;
     private Lineaproducto lineaproducto;
     private Sucursal sucursale;
     private String nombre;
     private String preciocompra;
     private String precioventa;
     private String descripcion;
     private String numeroserie;
     private String codigobarra;
     private String estado;
     private String unidadmedida;
     private String cantidad;
     private String medida;
     private String imagen;
     private Set movimientodets = new HashSet(0);

    public Producto() {
        this.id = 0;
        this.categoria = new Categoria();
        this.lineaproducto = new Lineaproducto();
        this.proveedor = new Proveedor();
        
        this.sucursale = new Sucursal();
    }

	
    public Producto(Proveedor proveedor, Categoria categoria, Lineaproducto lineaproducto,Sucursal sucursale, String nombre, String preciocompra, String descripcion, String estado, String cantidad) {
        this.proveedor = proveedor;
        this.categoria = categoria;
        this.lineaproducto = lineaproducto;
        
        this.sucursale = sucursale;
        
        this.nombre = nombre;
        this.preciocompra = preciocompra;
        this.descripcion = descripcion;
        this.estado = estado;
        this.cantidad = cantidad;
    }
    public Producto(Proveedor proveedor, Categoria categoria, Lineaproducto lineaproducto,Sucursal sucursale, String nombre, String preciocompra, String precioventa, String descripcion, String numeroserie, String codigobarra, String estado, String unidadmedida, String cantidad, String medida, String imagen, Set movimientodets) {
       this.proveedor = proveedor;
       this.categoria = categoria;
       this.lineaproducto = lineaproducto;
       
       this.sucursale = sucursale;
       
       this.nombre = nombre;
       this.preciocompra = preciocompra;
       this.precioventa = precioventa;
       this.descripcion = descripcion;
       this.numeroserie = numeroserie;
       this.codigobarra = codigobarra;
       this.estado = estado;
       this.unidadmedida = unidadmedida;
       this.cantidad = cantidad;
       this.medida = medida;
       this.imagen = imagen;
       this.movimientodets = movimientodets;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proveedor_id", nullable=false)
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="categoria_id", nullable=false)
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lineaproducto_id", nullable=false)
    public Lineaproducto getLineaproducto() {
        return this.lineaproducto;
    }
    
    public void setLineaproducto(Lineaproducto lineaproducto) {
        this.lineaproducto = lineaproducto;
    }
    

    
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sucursale_id", nullable=false)
    public Sucursal getSucursal() {
        return this.sucursale;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursale = sucursal;
    }
    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="preciocompra", nullable=false, length=45)
    public String getPreciocompra() {
        return this.preciocompra;
    }
    
    public void setPreciocompra(String preciocompra) {
        this.preciocompra = preciocompra;
    }
    
    @Column(name="precioventa", length=45)
    public String getPrecioventa() {
        return this.precioventa;
    }
    
    public void setPrecioventa(String precioventa) {
        this.precioventa = precioventa;
    }
    
    @Column(name="descripcion", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="numeroserie", length=45)
    public String getNumeroserie() {
        return this.numeroserie;
    }
    
    public void setNumeroserie(String numeroserie) {
        this.numeroserie = numeroserie;
    }
    
    @Column(name="codigobarra", length=45)
    public String getCodigobarra() {
        return this.codigobarra;
    }
    
    public void setCodigobarra(String codigobarra) {
        this.codigobarra = codigobarra;
    }
    
    @Column(name="estado", nullable=false, length=45)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    
    @Column(name="unidadmedida", length=45)
    public String getUnidadmedida() {
        return this.unidadmedida;
    }
    
    public void setUnidadmedida(String unidadmedida) {
        this.unidadmedida = unidadmedida;
    }
    
    @Column(name="cantidad", nullable=false, length=45)
    public String getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }
    
    @Column(name="medida", length=45)
    public String getMedida() {
        return this.medida;
    }
    
    public void setMedida(String medida) {
        this.medida = medida;
    }
    
    @Column(name="imagen", length=45)
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="producto")
    public Set getMovimientodets() {
        return this.movimientodets;
    }
    
    public void setMovimientodets(Set movimientodets) {
        this.movimientodets = movimientodets;
    }




}


